### ISSUE TITLE
Malformed Data 

### ISSUE THREAD

**Issue by boojew** [DeebotUniverse/Deebot-4-Home-Assistant#415]
### Checks

- [X] I have searched the existing issues and no issue is describing my issue
- [X] I have checked the [FAQ](https://deebot.readthedocs.io/home/faq/)
- [X] I have checked the [documentation](https://deebot.readthedocs.io/integrations/home-assistant)
- [X] I have installed/try to install the latest version

### The problem

Running 2.0.0 on HASS 2023.9.0b0 and I get this error when adding my X1 Omni. Region is CA and continent NA

<img width="553" alt="image" src="https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/1015566/2be6ad26-f65d-40e5-8c34-f00d599153f6">

### On which deebot vacuum you have the issue?

Omni X1

### Which version of the Deebot component are you using?

2.0.0.

### Which version of Home Assistant are you using?

2023.9.0b0

### What type of installation are you running?

Home Assistant Container

### Country

CA

### Continent

NA

### Instance type

Cloud

**Comment by edenhaus** [comment]
The bug existed directly in the frontend of Home Assistant and was fixed by https://github.com/home-assistant/frontend/pull/17822

**Comment by boojew** [comment]
Thanks. That seems to have been patched for frontend version https://github.com/home-assistant/frontend/releases/tag/20230905.0, but the issue persists. 
![image](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/1015566/ff4bd3ff-2916-4c2f-9649-3218c79aa89c)

Let's see if the next full release fixes it?

**Comment by edenhaus** [comment]
Did you clear the frontend cache after the upgrade?

**Comment by boojew** [comment]
Yes- and just upgraded to the official release. Same issue

**Comment by edenhaus** [comment]
Can you please verify what the frontend sends (via your browser's dev tools)?

Also try to clear the cache
![grafik](https://github.com/DeebotUniverse/Deebot-4-Home-Assistant/assets/26537646/590f1b32-5d6d-4007-8d11-cd29aff53133)

**Comment by edenhaus** [comment]
Will be fixed with https://github.com/home-assistant/frontend/pull/17868

**Comment by boojew** [comment]
After updating, clearing cache - no change.

**Comment by boojew** [comment]
Seems I didn’t have the right update. It’s solved now!
